CREATE TABLE Airplanes (
  ID INTEGER PRIMARY KEY NOT NULL,
  serial_number VARCHAR(20) UNIQUE NOT NULL,
  model_id INTEGER NOT NULL REFERENCES Models(ID),
  company_id INTEGER NOT NULL REFERENCES Companies(ID),
  created_at DATE DEFAULT "01.01.2000");

CREATE TABLE Airports (
  ID PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  code VARCHAR(3) UNIQUE NOT NULL,
  city_id INTEGER NOT NULL REFERENCES Cities(ID),
  country_id INTEGER NOT NULL REFERENCES Countries(ID));

CREATE TABLE Cities (
  ID INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(30),
  country_id INTEGER REFERENCES Countries(ID));

CREATE TABLE Companies (
  ID INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(100));

CREATE TABLE Countries (
  ID INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(50));

CREATE TABLE Employees (
  ID INTEGER PRIMARY KEY NOT NULL,
  full_name VARCHAR(100),
  position VARCHAR(100));

CREATE TABLE Flights (
  ID INTEGER PRIMARY KEY NOT NULL,
  airplane_id INTEGER REFERENCES Airplanes(ID),
  arrival_id INTEGER REFERENCES Airports(ID),
  departure_id INTEGER REFERENCES Airports(ID));

CREATE TABLE Models (
  ID INTEGER PRIMARY KEY NOT NULL,
  model VARCHAR(50) UNIQUE NOT NULL);

CREATE TABLE Passengers(
  person_id INTEGER NOT NULL REFERENCES Persons(ID),
  flight_id INTEGER NOT NULL REFERENCES Flights(ID));

CREATE TABLE Staff (
  employee_id INTEGER NOT NULL REFERENCES Employees(ID),
  flight_id INTEGER NOT NULL REFERENCES Flights(ID));




